---
language: ruby

os: osx
osx_image: xcode9.4

before_install:
  - rvm get head
  - gem install bundler

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - rbx-3
  - jruby-9.2.0.0
  - jruby-head

script: ./.travis.sh

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.2.0.0
    - rvm: rbx-3
